{{ ansible_managed|comment }}


# The password is not used for local connections and since i am not planning to
# expose the controller (w/o the need of tunneling) i do not need a password
# password = "$2$8czukueuidx55zmef8sjkxze6smu7urc$g614mwwh8az6q1951xqf7gxzyzmwuso9hximb3nzfzpqmsz7yycb"
# enable_password = "$2$8czukueuidx55zmef8sjkxze6smu7urc$g614mwwh8az6q1951xqf7gxzyzmwuso9hximb3nzfzpqmsz7yycb"
